### ISSUE TITLE
ansible run error

### ISSUE THREAD

**Issue by LeoHChen** [Blockdaemon/harmony-deploy#1]
Hit the following issue while running the main.yml.

Get our shard
ansible do_int() got an unexpected keyword argument 'base'"

I am using ansible 2.9.10

**Comment by nyetwurk** [comment]
Likely need to update jinja2
https://www.mail-archive.com/ansible-project%40googlegroups.com/msg45607.html
```
$ pip3 show jinja2
Name: Jinja2
Version: 2.11.2
Summary: A very fast and expressive template engine.
Home-page: https://palletsprojects.com/p/jinja/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /usr/local/lib/python3.8/site-packages
Requires: MarkupSafe
Required-by: ansible
```

This is for the `int(base=16)` call in `db.yml`

**Comment by LeoHChen** [comment]
Shall I update the jinja2 on the local host or the remote one?

**Comment by LeoHChen** [comment]
I see.  On my localhost running Amazon linux 2, the jinja2 is an older version.
```
Package python-jinja2-2.7.2-3.amzn2.noarch already installed and latest version
```

**Comment by nyetwurk** [comment]
Unfortunately, you may have to `pip3` or `sudo pip3` install jinja. Many of the python deb packages are horribly out of date due to lack of incentive (let alone expertise) to continue to make debian packages available without help from debian developers themselves.

**Comment by LeoHChen** [comment]
okay, upgraded jinja2, reinstall ansible using pip and it's working fine now.
